steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args: ["gsutil", "cp", "-r", "gs://greek-rnn-models/*", "./served_models/"]
    id: Download Models
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - "-f"
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - "--region=$_DEPLOY_REGION"
      - "--update-env-vars=^|^FRONTEND_ORIGINS=https://greek-lacuna-project.firebaseapp.com,https://greek-lacuna-project.web.app"
      - "--update-secrets=SESSION_SECRET_KEY=session-secret-key:latest"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run services describe $_SERVICE_NAME --region=$_DEPLOY_REGION --format='value(status.url)' > /workspace/cloud_run_url.txt
    id: Get Cloud Run URL
  - name: "node:22"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd frontend
        npm install
        echo "VITE_API_URL=$(cat /workspace/cloud_run_url.txt | tr -d '\n')/api" > .env.production
        npm run build
    id: Build Frontend
  - name: "node:22"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        npm install -g firebase-tools
        firebase deploy --only hosting --project=greek-lacuna-project
    id: Deploy Frontend

images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _DEPLOY_REGION: us-east4
  _AR_HOSTNAME: us-east4-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: greek-lacuna-project

  _TRIGGER_ID: c467d593-a83c-4649-8786-63c7e27828e7
  _PLATFORM: managed
  _SERVICE_NAME: greek-rnn
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - greek-rnn
